travis:
  secure:
    BINSTAR_TOKEN: AboKc0lqQVfO/99EAsCgyN5UgomT0VNUivoMLhLbcFBP9g+bxPRo/i83twSAjB6timQ4gIE7qXPgBd5ZWesUsoL3vtsrY/U4dcRSO1gOOiVFHJ8f5hyf7hm6siqc5+CMoSaBdg5p7bDlCsdX4J1TQRWyMsMNwCXiHw12BHWYFf+As213fJ3jyCF3TaIFRSI1T6n9zLoHLznJRLRIQdaYPiNxx7jQTD63KYg9mkCRR64KERWq4X9VoxkWcDN8TMv9ZaiXb78MiUfjCG3AMNrqffccZ6Zb92t3K4t5lUGbZSCOhQlZum64Aw8/aQ4rvoawdXc/XYYcONBjtmuSyU1GalT4msOV7/XrcFqoK6Dabo38G8m8yBqRCA3Y5oJZX1LIy6N+cwKblNZsy1noCMtX/pkd/0I2rMcvmoNyAy7287Z+h2GTZwiI2TT2KMtpvO0TdkeNTMfWPEGSRqx/YTHzXPUEuwT9XWUusJvwgnM7SzxPzCNRl5TSu3delgIN+NOjSLKpip+pGommML5JFy2O2Gb2L937NCId8oriZZxiAPEU0zE0eRfv8tg9YP/rvnn3EDPhuKX/BFktmL+08PC3YZ6A302mWm548IW2k1zK9PcroX4PjyIkxC3yrMsjze0iQMGEl7pvz8OGO2Z2JL/R/yLz18C3vX8OQ4LwPazI7Uo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
